baseURL = "https://ydgo.github.io/"
# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"
# 网站标题
title = "斗宗强者"
# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true


# 作者配置
[author]
  name = "斗宗"
  email = "yudongyyds@gmail.com"
  link = "ydgo.github.com"

# 菜单配置
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = "斗气大陆"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
  [[menu.main]]
      weight = 4
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = "关于"

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params]
    dateFormat = "2006-01-02"
    # which hash function used for SRI, when empty, no SRI is used
    # ["sha256", "sha384", "sha512", "md5"]
    # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
    # ["sha256", "sha384", "sha512", "md5"]
    fingerprint = "sha256"
    title = "斗宗强者的世界"
    description = "欢迎来到斗宗强者的世界，这里收藏了斗气世界许多强大的斗技..."
    # Header config
    # 页面头部导航栏配置
    [params.header]
        # desktop header mode ["fixed", "normal", "auto"]
        # 桌面端导航栏模式 ["fixed", "normal", "auto"]
        desktopMode = "fixed"
        # mobile header mode ["fixed", "normal", "auto"]
        # 移动端导航栏模式 ["fixed", "normal", "auto"]
        mobileMode = "auto"
    # 页面头部导航栏标题配置
        [params.header.title]
            # URL of the LOGO
            # LOGO 的 URL
            logo = ""
            # title name
            # 标题名称
            name = "斗气大陆"
            # you can add extra information before the name (HTML format is supported), such as icons
            # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
            pre = "<i class='fa-solid fa-fire-flame'></i>"
            # you can add extra information after the name (HTML format is supported), such as icons
            # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
            post = ""
            # whether to use typeit animation for title name
            # 是否为标题显示打字机动画
            typeit = false
    # Footer config
    # 页面底部信息配置
    [params.footer]
        enable = true
        # Custom content (HTML format is supported)
        # 自定义内容 (支持 HTML 格式)
        custom = ""
        # whether to show Hugo and theme info
        # 是否显示 Hugo 和主题信息
        hugo = true
        # whether to show copyright info
        # 是否显示版权信息
        copyright = true
        # whether to show the author
        # 是否显示作者
        author = true
        # site creation time
        # 网站创立年份
        since = 2023
        # ICP info only in China (HTML format is supported)
        # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
        # icp = '<a rel="license external nofollow noopener noreffer" href="https://beian.miit.gov.cn/" target="_blank">渝ICP备20005680号-1</a>'
        # license info (HTML format is supported)
        # 许可协议信息 (支持 HTML 格式)
        # license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

    # Section (all posts) page config
    # Section (所有文章) 页面配置
    [params.section]
        # special amount of posts in each section page
        # section 页面每页显示文章数量
        paginate = 20
        # date format (month and day)
        # 日期格式 (月和日)
        dateFormat = "01-02"
        # amount of RSS pages
        # RSS 文章数目
        rss = 10

    # List (category or tag) page config
    # List (目录或标签) 页面配置
    [params.list]
        # special amount of posts in each list page
        # list 页面每页显示文章数量
        paginate = 20
        # date format (month and day)
        # 日期格式 (月和日)
        dateFormat = "01-02"
        # amount of RSS pages
        # RSS 文章数目
        rss = 10

    # App icon config
    # 应用图标配置
    [params.app]
        # optional site title override for the app when added to an iOS home screen or Android launcher
        # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
        title = "斗气大陆"
        # whether to omit favicon resource links
        # 是否隐藏网站图标资源链接
        noFavicon = false
        # modern SVG favicon to use in place of older style .png and .ico files
        # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
        svgFavicon = ""
        # Android browser theme color
        # Android 浏览器主题色
        themeColor = "#ffffff"
        # Safari mask icon color
        # Safari 图标颜色
        iconColor = "#5bbad5"
        # Windows v8-11 tile color
        # Windows v8-11 磁贴颜色
        tileColor = "#da532c"

    # Search config
    # 搜索配置
    [params.search]
        enable = true
        # type of search engine ["lunr", "algolia"]
        # 搜索引擎的类型 ["lunr", "algolia"]
        type = "lunr"
        # max index length of the chunked content
        # 文章内容最长索引长度
        contentLength = 4000
        # placeholder of the search bar
        # 搜索框的占位提示语
        placeholder = ""
        # max number of results length
        # 最大结果数目
        maxResultLength = 10
        # snippet length of the result
        # 结果内容片段长度
        snippetLength = 30
        # HTML tag name of the highlight part in results
        # 搜索结果中高亮部分的 HTML 标签
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        # 是否在搜索索引中使用基于 baseURL 的绝对路径
        absoluteURL = false
        [params.search.algolia]
        index = ""
        appID = ""
        searchKey = ""


    # 主页配置
    [params.home]
        # LoveIt 新增 | 0.2.0 RSS 文章数目
        rss = 10
        # 主页个人信息
        [params.home.profile]
            enable = true
            # Gravatar 邮箱，用于优先在主页显示的头像
            gravatarEmail = ""
            # 主页显示头像的 URL
            avatarURL = "/img/avatar.png"
            # LoveIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
            title = "斗宗强者"
            # 主页显示的网站副标题 (允许 HTML 格式)
            subtitle = "斗宗强者，恐怖如斯"
            # 是否为副标题显示打字机动画
            typeit = true
            # 是否显示社交账号
            social = true
            # LoveIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
            disclaimer = ""
            # 主页文章列表
            [params.home.posts]
                enable = true
                # 主页每页显示文章数量
                paginate = 6
                # LoveIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
                # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
                defaultHiddenFromHomePage = false

    [params.social]
        GitHub = "ydgo"
        Email = "yudongyyds@gmail.com"

    [params.page]
        # LoveIt 新增 | 0.2.0 是否在主页隐藏一篇文章
        hiddenFromHomePage = false
        # LoveIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
        hiddenFromSearch = false
        # LoveIt 新增 | 0.2.0 是否使用 twemoji
        twemoji = false
        # 是否使用 lightgallery
        lightgallery = false
        # LoveIt 新增 | 0.2.0 是否使用 ruby 扩展语法
        ruby = true
        # LoveIt 新增 | 0.2.0 是否使用 fraction 扩展语法
        fraction = true
        # LoveIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
        fontawesome = true
        # 是否在文章页面显示原始 Markdown 文档链接
        linkToMarkdown = true
        # LoveIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
        rssFullText = false
        # LoveIt 新增 | 0.2.0 目录配置
        [params.page.toc]
            # 是否使用目录
            enable = true
            # LoveIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
            keepStatic = true
            # 是否使侧边目录自动折叠展开
            auto = true
        # LoveIt 新增 | 0.2.0 代码配置
        [params.page.code]
            # 是否显示代码块的复制按钮
            copy = true
            # 默认展开显示的代码行数
            maxShownLines = 50
        # KaTeX mathematical formulas config (KaTeX https://katex.org/)
        # KaTeX 数学公式配置 (KaTeX https://katex.org/)
        [params.page.math]
            enable = false
            # default inline delimiter is $ ... $ and \( ... \)
            # 默认行内定界符是 $ ... $ 和 \( ... \)
            inlineLeftDelimiter = ""
            inlineRightDelimiter = ""
            # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
            # 默认块定界符是 $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} 和一些其它的函数
            blockLeftDelimiter = ""
            blockRightDelimiter = ""
            # KaTeX extension copy_tex
            # KaTeX 插件 copy_tex
            copyTex = true
            # KaTeX extension mhchem
            # KaTeX 插件 mhchem
            mhchem = true
        # Mapbox GL JS config (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
        # Mapbox GL JS 配置 (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
        [params.page.mapbox]
            # access token of Mapbox GL JS
            # Mapbox GL JS 的 access token
            accessToken = ""
            # style for the light theme
            # 浅色主题的地图样式
            lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
            # style for the dark theme
            # 深色主题的地图样式
            darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
            # whether to add NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
            # 是否添加 NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
            navigation = true
            # whether to add GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
            # 是否添加 GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
            geolocate = true
            # whether to add ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
            # 是否添加 ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
            scale = true
            # whether to add FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
            # 是否添加 FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
            fullscreen = true

        [params.page.share]
            enable = false

        # Comment config
        # 评论系统设置
        [params.page.comment]
            enable = false
            # Disqus comment config (https://disqus.com/)
            # Disqus 评论系统设置 (https://disqus.com/)
            [params.page.comment.disqus]
            enable = false
            # Disqus shortname to use Disqus in posts
            # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
            shortname = ""
        # Gitalk comment config (https://github.com/gitalk/gitalk)
        # Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
        [params.page.comment.gitalk]
            enable = false
            owner = ""
            repo = ""
            clientId = ""
            clientSecret = ""
        # Valine comment config (https://github.com/xCss/Valine)
        # Valine 评论系统设置 (https://github.com/xCss/Valine)
        [params.page.comment.valine]
            enable = false
            appId = ""
            appKey = ""
            placeholder = ""
            avatar = "mp"
            meta= ""
            pageSize = 10
            # automatically adapt the current theme i18n configuration when empty
            # 为空时自动适配当前主题 i18n 配置
            lang = ""
            visitor = true
            recordIP = true
            highlight = true
            enableQQ = false
            serverURLs = ""
            # emoji data file name, default is "google.yml"
            # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
            # located in "themes/LoveIt/assets/lib/valine/emoji/" directory
            # you can store your own data files in the same path under your project:
            # "assets/lib/valine/emoji/"
            # emoji 数据文件名称, 默认是 "google.yml"
            # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
            # 位于 "themes/LoveIt/assets/lib/valine/emoji/" 目录
            # 可以在你的项目下相同路径存放你自己的数据文件:
            # "assets/lib/valine/emoji/"
            emoji = ""

        # Facebook comment config (https://developers.facebook.com/docs/plugins/comments)
        # Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
        [params.page.comment.facebook]
            enable = false
            width = "100%"
            numPosts = 10
            appId = ""
            # automatically adapt the current theme i18n configuration when empty
            # 为空时自动适配当前主题 i18n 配置
            languageCode = ""
        # Telegram comments config (https://comments.app/)
        # Telegram comments 评论系统设置 (https://comments.app/)
        [params.page.comment.telegram]
            enable = false
            siteID = ""
            limit = 5
            height = ""
            color = ""
            colorful = true
            dislikes = false
            outlined = false
        # Commento comment config (https://commento.io/)
        # Commento comment 评论系统设置 (https://commento.io/)
        [params.page.comment.commento]
            enable = false
        # utterances comment config (https://utteranc.es/)
        # utterances comment 评论系统设置 (https://utteranc.es/)
        [params.page.comment.utterances]
            enable = false
            # owner/repo
            repo = ""
            issueTerm = "pathname"
            label = ""
            lightTheme = "github-light"
            darkTheme = "github-dark"

        # giscus comment config (https://giscus.app/)
        # giscus comment 评论系统设置 (https://giscus.app/zh-CN)
        [params.page.comment.giscus]
            # You can refer to the official documentation of giscus to use the following configuration.
            # 你可以参考官方文档来使用下列配置
            enable = false
            repo = ""
            repoId = ""
            category = "Announcements"
            categoryId = ""
            # automatically adapt the current theme i18n configuration when empty
            # 为空时自动适配当前主题 i18n 配置
            lang = ""
            mapping = "pathname"
            reactionsEnabled = "1"
            emitMetadata = "0"
            inputPosition = "bottom"
            lazyLoading = false
            lightTheme = "light"
            darkTheme = "dark"
        # Third-party library config
        # 第三方库配置
        [params.page.library]
            [params.page.library.css]
                # someCSS = "some.css"
                # located in "assets/" 位于 "assets/"
                # Or 或者
                # someCSS = "https://cdn.example.com/some.css"
            [params.page.library.js]
                # someJavascript = "some.js"
                # located in "assets/" 位于 "assets/"
                # Or 或者
                # someJavascript = "https://cdn.example.com/some.js"
        # Page SEO config
        # 页面 SEO 配置
        [params.page.seo]
            # image URL
            # 图片 URL
            images = []
            # Publisher info
            # 出版者信息
        [params.page.seo.publisher]
            name = ""
            logoUrl = ""


    # TypeIt config
    # TypeIt 配置
    [params.typeit]
        # typing speed between each step (measured in milliseconds)
        # 每一步的打字速度 (单位是毫秒)
        speed = 100
        # blinking speed of the cursor (measured in milliseconds)
        # 光标的闪烁速度 (单位是毫秒)
        cursorSpeed = 1000
        # character used for the cursor (HTML format is supported)
        # 光标的字符 (支持 HTML 格式)
        cursorChar = "|"
        # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
        # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
        duration = -1

    # Site verification code for Google/Bing/Yandex/Pinterest/Baidu
    # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
    [params.verification]
        google = ""
        bing = ""
        yandex = ""
        pinterest = ""
        baidu = ""

        # Site SEO config
        # 网站 SEO 配置
        [params.seo]
        # image URL
        # 图片 URL
        image = "/img/jinx.png"
        # thumbnail URL
        # 缩略图 URL
        thumbnailUrl = ""
[outputs]
    home = ["HTML", "RSS", "JSON"]